loader:
  class: \Twig\Loader\FilesystemLoader
  arg:
    - "./templates"

twig:
  class: Twig\Environment
  arg:
    - "@loader"

controller.main:
  class: App\Controller\MainController
  arg:
    - '@twig'

router:
  class: Sruuua\Routing\RouterBuilder
  func:
    - registerController:
        - controller.main